### PR TITLE
Force ggplots build

### PR DESCRIPTION
**Pull request by karldw**
I noticed that the ggplot calls in the tests weren't getting evaluated, so I added `ggplot_build` to each one. I also broke up the `expect_silent` because I had a hard time seeing what was going on. Please let me know if you'd like any changes!

With these changes, the tests aren't passing. It seems like all the error messages are along the lines of `Warning: Removed 4 rows containing non-finite values (stat_count)`, which doesn't seem like a huge problem.

### CODE REVIEW

**Comment by const-ae** [comment]
Good catch, it is definitely not intentional that the plots aren't actually build.

However, breaking the tests is also problematic. I guess the problem is wrapping calls like
```
ggplot(mtcars, aes(x=list_col)) +
    geom_bar() +
    scale_x_upset(n_intersections = 5)
```
that generate a warning in `testthat::expect_silent()`.

This relates to the problem how to unit test a plotting package. I cannot use `testthat::expect_equal()` to specify what the output should look like. So the best I can do is to make some plots and make sure there are no errors. Wrapping all calls in `testthat::expect_silent()` is just my workaround so that something turns green.

I think the proper way to handle the situation is to proceed as you suggest in the PR and then either

1. Find the source of the warnings and see if they can be eliminated
2. Don't wrap the calls that produce a warning in `testthat::expect_silent()`.

Of course (1) is the better option, but if you do (2) I would also be fine with that.

**Comment by karldw** [comment]
It is possible to test graphics output with tools like `vdiffr::expect_doppelganger`. I'm not sure how much effort is involved; it definitely seems more difficult than regular `expect_equals` tests.

A third option is to `skip` the failing tests. I'm happy to do (2) or (3) for now.

**Comment by const-ae** [comment]
Wow, the `vdiffr::expect_doppelganger()` thing is amazing and I will consider implementing that in the future.
For now, I think I prefer the (2) option, so if you remove the `expect_silent()` calls from the calls that generate warnings, I am happy to merge the PR.

**Comment by const-ae** [comment]
I merged your PR. Thank you again for making the effort to improve this package :)

**Pull request merged**
